INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (1, 'Matemáticas', 'Estudio de números, álgebra, geometría y cálculo.');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (2, 'Español', 'Lengua castellana: gramática, ortografía, literatura y redacción.');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (3, 'Inglés', 'Idioma extranjero: comprensión oral, lectura, escritura y conversación.');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (4, 'Ciencias Naturales', 'Estudio del cuerpo humano, seres vivos, la materia y el medio ambiente.');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (5, 'Ciencias Sociales', 'Historia, geografía, democracia y cultura ciudadana.');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (6, 'Educación Física', 'Actividad física, deportes, salud corporal y trabajo en equipo.');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (7, 'Religión', 'Estudio de valores, espiritualidad y religiones del mundo.');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (8, 'Ética y Valores', 'Desarrollo del pensamiento crítico, moral y principios éticos.');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (9, 'Tecnología e Informática', 'Competencias digitales, programación y uso de herramientas tecnológicas.');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (10, 'Artes', 'Expresión artística a través de la pintura, escultura, danza y música.');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (11, 'Física', 'Estudio de la materia, energía, movimiento y leyes naturales.');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (12, 'Química', 'Estudio de sustancias, reacciones químicas y estructura de la materia.');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (13, 'Biología', 'Estudio de los seres vivos, genética, evolución y ecología.');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (14, 'Filosofía', 'Reflexión crítica sobre el ser humano, el conocimiento y la existencia.');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (15, 'Emprendimiento', 'Formación en liderazgo, innovación y creación de empresas.');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (16, 'MATEMATICAS', 'Asignatura enfocada en el estudio de números, estructuras, espacios y cambios');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (17, 'LENGUA CASTELLANA', 'Estudio del idioma español, su gramática, literatura y comunicación');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (18, 'CIENCIAS NATURALES', 'Estudio de los fenómenos naturales y la vida en la Tierra');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (19, 'FISICA', 'Ciencia que estudia la materia, energía y sus interacciones');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (20, 'FILOSOFIA', 'Estudio de cuestiones fundamentales sobre la existencia, conocimiento y ética');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (21, 'EDUCACION FISICA', 'Desarrollo de habilidades físicas y promoción de vida saludable');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (22, 'EDUCACION ARTISTICA', 'Desarrollo de la creatividad y expresión a través de diversas formas artísticas');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (23, 'ETICA, CIA Y CATEDRA DE LA PAZ', 'Formación en valores éticos, ciudadanía y construcción de paz');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (24, 'MENTALIDAD EMPRESARIAL', 'Desarrollo de habilidades para emprender y gestionar proyectos');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (25, 'INGLES', 'Aprendizaje del idioma inglés y su cultura');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (26, 'QUIMICA', 'Estudio de la composición, estructura y propiedades de la materia');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (27, 'EDUCACION RELIGIOSA', 'Estudio de las tradiciones religiosas y su impacto cultural');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (28, 'TECNOLOGIA Y ROBOTICA', 'Desarrollo de habilidades técnicas y diseño de soluciones tecnológicas');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (29, 'HISTORIA', 'Estudio de eventos pasados y su impacto en la sociedad');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (30, 'GEOGRAFIA', 'Estudio de la Tierra, sus características físicas y las sociedades humanas');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (31, 'DIMENSION COGNITIVA', 'Desarrollo de procesos mentales y habilidades de pensamiento');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (32, 'DIMENSION COMUNICATIVA', 'Desarrollo de habilidades de expresión y comunicación');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (33, 'DIMENSION ESPIRITUAL', 'Exploración de valores trascendentales y sentido de vida');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (34, 'DIMENSION ESTETICA Y CORPORAL', 'Desarrollo de la apreciación artística y conciencia corporal');
INSERT INTO desarrollo_de_aprendisaje.asignatura (id_asignatura, nombre, descripcion) VALUES (35, 'DIMENSION SOCIO-AFECTIVA', 'Desarrollo de habilidades sociales y manejo emocional');
